<?php
$title = 'Edit Tag';
$this->headTitle($title);
//var_dump($this->form->getElement('name')); exit;
?>
<div class="row">

    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
            </div>
            <div class="panel-body">
                <form method="POST" action="<?php echo $this->url('tag-edit', array('id' => $this->tag->getId()))?>">
                <div class="form-group">
                    <?php
                    echo $this->form;
                    ?>
                </div>

                <div class="form-group">
                    <?php
                    echo $this->form->getElement('submit');
                    ?>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>



