<div class="row">

    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Speakaboos Videos</h3>
            </div>
            <div class="panel-body">
                <table class="table" data-toggle="table">
                    <thead>
                        <tr>
                            <th>Video Title</th>
                            <th>Tags</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($this->videos as $video):?>

                        <tr>
                            <td>
                                <a href="<?php echo $this->url('video-view', array('id' => $video->getId()))?>">
                                    <?php echo $video->getTitle();?>
                                </a>
                            </td>
                            <td>
                                <?php
                                $videoTags = $video->getVideoTags()->toArray();
                                $tags = '';
                                foreach($videoTags as $key => $videoTag){
                                    $tags .= $videoTag->getTag()->getName();
                                    if (next($videoTags)==true) $tags .= ", ";
                                }
                                echo $tags;
                                ?>
                            </td>
                            <td>
                                <a href="<?php echo $this->url('video-edit', array('id' => $video->getId()))?>">Edit</a>
                                -
                                Delete
                            </td>

                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

